#!/usr/bin/env python

import sys
from os.path import expanduser
import urllib2
import xml.etree.ElementTree as ET
import datetime
from optparse import OptionParser
import re

usage = "usage: %prog [user] [options]"
parser = OptionParser(usage=usage)

parser.add_option("-p", "--penalties",
                  action="store_true", dest="show_penalties",
                  help="Display user's penalties")

parser.add_option("-i", "--items",
                  action="store_true", dest="show_items",
                  help="Display user's items")

(options, args) = parser.parse_args()

user = ''
try:
    home = expanduser("~")
    with open(home + "/.idlerpguser") as userfile:
        user = userfile.read()
except (EOFError, IOError) as e:
    user = ''

if args:
    user = args[0]

if not user:
    print "Either specify a username or put a default username in ~/.idlerpguser"
    sys.exit(1)

url = "http://xethron.lolhosting.net/xml.php?player={0}".format(user)

# Recent Modifiers
# This code was placed here so that all text could appear at once
response = urllib2.urlopen(url)
xml = response.read()
player = ET.fromstring(xml)
mod_url = "http://xethron.lolhosting.net/playerview.php?player={0}"
mod_url = mod_url.format(user)
response = urllib2.urlopen(mod_url).read()

pattern = re.compile("\[\d+/\d+/\d+.*\.")
recent = re.findall(pattern, response)
# End recent modifiers

if not player.find('username').text:
    print "Not a valid username"
    sys.exit(1)

mod_url = "http://xethron.lolhosting.net/playerview.php?player={0}"
mod_url = mod_url.format(user)
response = urllib2.urlopen(mod_url).read()

pattern = re.compile("(\[\d+/\d+/\d+ \d{2}:\d{2}:\d{2}\])(.*\.)")
recent = re.findall(pattern, response)

def parse_ttl(seconds):
    return str(datetime.timedelta(seconds=int(seconds)))

def parse_align(alignment):
    if alignment == 'g':
        return "Good"
    elif alignment == 'e':
        return "Evil"
    else:
        return "Neutral"

print """\033[1m{0}\033[0m
\033[4mClass\033[0m: {1}
\033[4mLevel\033[0m: {2}
\033[4mTime to next level\033[0m: {3}
\033[4mOnline\033[0m: {4}
\033[4mx-position\033[0m: {5}
\033[4my-position\033[0m: {6}
\033[4mAllignment\033[0m: {7}""".format(player.find('username').text,
                                        player.find('class').text,
                                        player.find('level').text,
                                        parse_ttl(player.find('ttl').text),
                                        bool(player.find('online').text),
                                        player.find('xpos').text,
                                        player.find('ypos').text,
                                        parse_align(player.find('alignment').text))

if options.show_penalties:
    print "\n\033[4mPenalties\033[0m:"
    penalties = player.find('penalties')
    for penalty in penalties:
        print "{0}: {1}".format(penalty.tag, penalty.text)

if options.show_items:
    print "\n\033[4mItems\033[0m:"
    items = player.find('items')
    for item in items:
        print "{0}: {1}".format(item.tag, item.text)

# Ha! Fooled you! More Recent Modifier stuff here
print ''
for r in recent:
    print " * \033[41m\033[37m{0}\033[0m {1}".format(r[0], r[1])
# All done for reals this time.
